### ISSUE TITLE
More models/algorithms

### ISSUE THREAD

**Issue by mospring** [MLOntology/MLO#1]
Thanks for working on a machine learning ontology.
Wanting to use the models in my knowledge graph, I found a few important but missing concepts:

- Symbolic regression (has been around for decades)
- Regularized regression (which encompasses all kernel type regression)
- LASSO
- Compressed Sensing (yes some may not regard it as ML but it is used that way)

You may consider adding these models.

**Comment by JuliaoBraga** [comment]
Dear Maja,

Thank you very much for your kindness in recommending these topics. We will consider them in due course. 

We are currently focused on growing the topology with applications and relationships of Machine Learning with Internet Infrastructure. But we are working hard on aligning topologies in such a way that we can encourage contributions from contributors to populate our knowledge base. Perhaps details can be seen here; https://frenxiv.org/rc954/. Two other papers, much more complete, are in the final stages for publication, and we will make them available soon.

Juliao Braga
---
http://braga.net.br/

**Comment by fasr** [comment]
> Dear Maja,
> 
> Thank you very much for your kindness in recommending these topics. We will consider them in due course.
> 
> We are currently focused on growing the topology with applications and relationships of Machine Learning with Internet Infrastructure. But we are working hard on aligning topologies in such a way that we can encourage contributions from contributors to populate our knowledge base. Perhaps details can be seen here; https://frenxiv.org/rc954/. Two other papers, much more complete, are in the final stages for publication, and we will make them available soon.
> 
> ## Juliao Braga
> http://braga.net.br/

These methods belong into statistical learning?
